

name: op
root: ~/

# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: sudo /etc/rc.d/mysqld start

# Project hooks
# Runs on project start, always
# on_project_start: command
# Run on project start, the first time
# on_project_first_start: command
# Run on project start, after the first time
# on_project_restart: command
# Run on project exit ( detaching from tmux session )
# on_project_exit: command
# Run on project stop
# on_project_stop: command

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
# startup_window: editor

# Specifies (by index) which pane of the specified window will be selected on project startup. If not set, the first pane is used.
# startup_pane: 1

# Controls whether the tmux session should be attached to automatically. Defaults to true.
# attach: false

# Runs after everything. Use it to attach to tmux with custom options etc.
# post: tmux -CC attach -t op
windows: 
  - server-1:
          - cd ~/op/sakura-server-1 && clear && CODENAME=kyoko bundle exec rails s
  - window2:
          - cd ~ && clear
  - window3:
          - cd ~ && clear
  - window4:
          - cd ~ && clear
  - resource:
          - cd ~/op/sakura-resource-zh-TW && clear
  - archive:
          - cd ~/op/sakura-archive-all && clear
  - master-data:
          - cd ~/op/sakura-master-data && clear
  - script:
    - cd ~/op/sakura-archive-script && clear
  - wiki:
          - cd ~/op/sakura-client.wiki && clear
  - yoshino:
      layout: main-horizontal
      panes:
        - clear && cd ~/op/yoshino/ && RAILS_ENV=production bundle exec rails s
        - clear && cd ~ && ssh op-stage-db.5ml.io && cd yoshino-service
